### ISSUE TITLE
Scanning on linux can cause memory problems

### ISSUE THREAD

**Issue by targodan** [fkie-cad/yapscan#25]
## The Problem

Scanning processes on linux can cause memory problems.

In cases where a process mmaps files, but only accesses small parts of this file, the memory footprint (RSS) will only consist of the accessed pages. This can be orders of magnitudes smaller than the size of the mapped file. If we now scan the target process in full, we access all pages of all mmap'ed files, leading the kernel to load them into memory and the RSS will rise to the full size of the file. Doing this on many processes can ultimately lead to a crash of the system due to OOM.

## The Solution

@hillu has developed an [elegant workaround](
https://github.com/VirusTotal/yara/commit/063cbfb793a9bbf2d996c83a66d8713b0e0e3e1c), where they detect this case of an mmap'ed file, then proceeds to mmap the same file for scanning and only access the dirty pages from the target process. This is sufficient since only accessed pages can be modified by the target process and thus only those pages may vary from the file content.

**Comment by targodan** [comment]
Fixed in 6a851fd04078792647861cf151e203d130d8652f

**Comment by hillu** [comment]
If anyone knows how to do the same thing on Windows, I'd be very interested to hear about it.

So far, I know how to get the file associated with a mapping and I know how to determine whether a page within such a mappimg has been changed (`NtQueryVirtualMemory` using `MemoryMappedFilenameInformation`, `MemoryWorkingSetExInformation`, respectively). What's missing is: How do I get the original offset in the on-disk file that corresponds to a given page?

**Comment by targodan** [comment]
Sadly I don't have an answer either. I'm closing this issue since it has been resolved in the 0.17.0 release. If you want, feel free to open a discussion for a windows solution. :)
