### ISSUE TITLE
Feature request: crash option (for memdump)

### ISSUE THREAD

**Issue by sigillaria** [fkie-cad/yapscan#6]
Perhaps like so: `yapscan crash pid`.
Yapscan then injects a thread in the process of pid and makes it segfault. 
A nice windbg-supporting memdump *.dmp will be created and can be used for analysis.

**Comment by targodan** [comment]
Will be implemented soon :tm:

**Comment by targodan** [comment]
Is implemented in the most recent version. Crashing remote processes works by starting a new remote thread at address `0`, which causes a segfault.

Note that only services can inject into services and only regular processes into regular processes. To remedy this, there is also a (so far) undocumented `as-service` command, which installs yapscan as a service and then executes the desired command.

Example: `yapscan as-service crash <pid>`
